Add tests for auth and LayerBuilder LayerBuilder's test would not pass since TypeError: require.context is not a function However, this seems like an issue with web-pack compatibility with jest.